vim9script

set nocompatible

# vim-plug
var data_dir = has('nvim') ? stdpath('data') .. '/site' : '~/.vim'
if empty(glob(data_dir .. '/autoload/plug.vim'))
  silent execute '!curl -fLo ' .. data_dir .. '/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

g:plug#begin('~/.vim/bundle')
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'SirVer/ultisnips'
Plug 'davidhalter/jedi-vim', { 'for': 'python' }
Plug 'dense-analysis/ale'
Plug 'elixir-editors/vim-elixir'
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'flazz/vim-colorschemes'
Plug 'godlygeek/tabular'
Plug 'honza/vim-snippets'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'lervag/vimtex', { 'for': 'tex' }
Plug 'lervag/wiki-ft.vim'
Plug 'lervag/wiki.vim'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'ocaml/vim-ocaml'
Plug 'prabirshrestha/vim-lsp'
Plug 'rodjek/vim-puppet'
Plug 'rust-lang/rust.vim'
Plug 'sainnhe/gruvbox-material'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dadbod'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ziglang/zig.vim'
g:plug#end()

source ~/.vim/myfiles/myvimsetup.vim
source ~/.vim/myfiles/mypluginsettings.vim
source ~/.vim/myfiles/mykeybindings.vim
source ~/.vim/myfiles/ocamlmycaml.vim

runtime ftplugin/man.vim
packadd! matchit
